### PR TITLE
completes #5 - support app arguments

### PR DESCRIPTION
**Pull request by tunnckoCore**
Refers to #4 #5 
I think it would work. Im on Linux and work.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Actually when thinking about it. The Firefox thing shouldn't be a problem. It's up to the user to specify that right. http://superuser.com/questions/413939/how-to-start-a-program-with-command-line-arguments-on-windows-cmd-with-start

So basically: `opn('http://sindresorhus.com', ['firefox', '-option "argument"']);`

Yes, it will not be cross-platform, but there's just no way to achieve that when apps behave differently regarding arguments on different platforms.

I think this is a good middle ground.

Thoughts?

**Comment by sindresorhus** [comment]
@tunnckoCore :arrow_up:

**Comment by tunnckoCore** [comment]
Sorry for the delay.

Yep. But this `['firefox', '-option "argument"']);` is ugly.

As I remember (and see now test cases) it works on linux and os x. I'll check again tests.

And we need some windows guru, hxahxhahxa

**Comment by sindresorhus** [comment]
> is ugly.

I'm surprised you're surprised. It's Windows after all.

**Comment by tunnckoCore** [comment]
ohh yea, right, lol

**Comment by tunnckoCore** [comment]
@sindresorhus 
Hmm.. maybe [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) should help?

**Comment by sindresorhus** [comment]
How exactly?

**Comment by arthurvr** [comment]
ping @tunnckoCore and @asbjornenge. Anyone of you interested in completing this PR or #8?

**Comment by tunnckoCore** [comment]
@arthurvr how? Windows sucks. We need additions to this PR to handle them correctly, also need setup for windows build testing

**Comment by asbjornenge** [comment]
I could clean up #8 ref. @sindresorhus comments about syntax. But would it then be merged? And if it would work on windows I have no clue. Nor any means of testing.

**Comment by tunnckoCore** [comment]
>  And if it would work on windows I have no clue.

that's the problem, we need testing before merge anything. syntax isnt a problem, it is the easiest thing.

**Comment by sindresorhus** [comment]
Yeah, don't worry about code style. I can just fix that later on. The hold up here is having it work cross-platform and manually testing on all platforms.

**Comment by tunnckoCore** [comment]
> The hold up here is having it work cross-platform and manually testing on all platforms.

mm maybe. and it's not a problem to setup appveyor for testing.

mostly the case is how we should handle these few possible ways of defining arguments in windows and what variant should we limit.

**Comment by tunnckoCore** [comment]
@asbjornenge see https://github.com/sindresorhus/opn/pull/6#issuecomment-67875808

**Comment by sindresorhus** [comment]
> Yep. But this ['firefox', '-option "argument"']); is ugly.

I agree, but we can't really support every app specific way to do args on Windows.

**Comment by kevva** [comment]
@tunnckoCore , if the PR is as complete as it gets as of now, I can test it on Windows.

**Comment by tunnckoCore** [comment]
Mmm nope, imo it is not complete atm, b/c https://github.com/sindresorhus/opn/pull/6#issuecomment-67802183 - just noticed that, they should be changed then we can test.

I will come with some pull-and-commits after dinner.

**Comment by sindresorhus** [comment]
fixed in 2.0.0 => https://github.com/sindresorhus/opn/commit/55e6dac9264dc02844b64a870f1d6d40160452a9

**Pull request closed without merging**
